services:
  php:
    image: php:8.4-cli
    volumes:
    - .:/app:rw
    working_dir: /app
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    command: start-dev
    platform: linux/amd64
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8088:8080'
