on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: PHP Unit

jobs:
  Unit:
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage

    strategy:
      matrix:
        php: [8.4]

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit
