on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Analysis

jobs:
  Analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.4 ]

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: composer phpstan

      - name: Run pint
        run: composer fix
